- pairs:
    spot:
      - MRE7BTC/USD
      - MRE7YIELD/USD
      - USDC/USD
      - LBTC/USD
      - UNIBTC/USD
      - WBTC/USD
      - BTC/USD
      - SURVIVOR/USD
      - STRK/USD
      - SUSN/USD
      - USDT/USD
      - USN/USD
      - ETH/USD
      - WSTETH/USD
      - EKUBO/USD
  time_difference: 600
  price_deviation: 0.03
