- pairs:
    spot:
      - BTC/USD
      - ETH/USD
      - ETH/STRK
      - SOL/USD
      - BNB/USD
      - LTC/USD
      - LINK/USD
      - AVAX/USD
      - MATIC/USD
      - XRP/USD
      - DOGE/USD
      - 1000PEPE/USD
      - AAVE/USD
      - TRX/USD
      - SUI/USD
      - WIF/USD
      - TIA/USD
      - TON/USD
      - LDO/USD
      - ARB/USD
      - OP/USD
      - ORDI/USD
      - JTO/USD
      - JUP/USD
      - UNI/USD
      - OKB/USD
      - ATOM/USD
      - NEAR/USD
      - 1000SATS/USD
      - ONDO/USD
      - STRK/USD
      - BCH/USD    
      - WBTC/USD   
      - WSTETH/USD 
      - STETH/USD  
      - NSTR/USD   
      - LORDS/USD  
      - ZEND/USD   
      - EKUBO/USD  
      - SHIB/USD   
      - CRV/USD    
      - BROTHER/USD
      - POPCAT/USD 
      - SEI/USD    
      - FTM/USD    
      - GOAT/USD   
      - MOODENG/USD
      - BONK/USD   
      - LUSD/USD   

    future:
      - BTC/USDT
      - ETH/USDT
      - SOL/USDT
      - BNB/USDT
      - LTC/USDT
      - LINK/USDT
      - AVAX/USDT
      - MATIC/USDT
      - XRP/USDT
      - DOGE/USDT
      - 1000PEPE/USDT
      - AAVE/USDT
      - TRX/USDT
      - SUI/USDT
      - WIF/USDT
      - TIA/USDT
      - TON/USDT
      - LDO/USDT
      - ARB/USDT
      - OP/USDT
      - ORDI/USDT
      - JTO/USDT
      - JUP/USDT
      - UNI/USDT
      - OKB/USDT
      - ATOM/USDT
      - NEAR/USDT
      - 1000SATS/USDT
      - ONDO/USDT
      - STRK/USD
      - BCH/USDT   
      - WBTC/USDT  
      - WSTETH/USDT
      - STETH/USDT 
      - NSTR/USDT  
      - LORDS/USDT 
      - ZEND/USDT  
      - EKUBO/USDT 
      - SHIB/USDT  
      - CRV/USDT   
      - POPCAT/USDT
      - SEI/USDT   
      - FTM/USDT   
      - GOAT/USDT  
      - MOODENG/USDT
      - BONK/USDT  
      - LUSD/USDT  

  time_difference: 1
  price_deviation: 0.025