- pairs:
    spot:
      - BTC/USD
      - BTC/EUR
      - WBTC/USD
      - WBTC/BTC
      - ETH/USD
      - STRK/USD
      - USDC/USD
      - USDT/USD
      - DAI/USD
      - DOG/USD
      - LBTC/USD
  time_difference: 600
  price_deviation: 0.005

- pairs:
    spot:
      - STETH/USD
      - LORDS/USD
      - NSTR/USD
      - EKUBO/USD
      - BROTHER/USDPLUS
      - XSTRK/USD
      - SSTRK/USD
      - WSTETH/USD
      - MRE7YIELD/USD
      - MRE7BTC/USD
      - UNIBTC/USD
      - USN/USD
      - SUSN/USD
      - SURVIVOR/USD
  time_difference: 1200
  price_deviation: 0.025
